- name: Deploy Tomcat
  hosts: web
  become: yes

  tasks:
    - name: Source to destination
      copy:
        src: "/var/snap/jenkins/5022/workspace/ansibleprac/target/ansibleprac.war"
        dest: "/opt/tomcat/webapps/ansibleprac.war"
        remote_src: no

    - name: Shutdown Tomcat
      shell: /opt/tomcat/bin/shutdown.sh

    - name: Startup Tomcat
      shell: /opt/tomcat/bin/startup.sh
